[package]
name = "fpe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = "0.10.56"
byteorder = "1.4.3"

[dev-dependencies]
bencher = "0.1.5"

[[bench]]
name = "ff1"
harness = false
